# Generated by Django 4.2.4 on 2024-02-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_reports_quantity_reports_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
