# Generated by Django 4.2.4 on 2024-02-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Crop', 'Crop'), ('Herb', 'Herb'), ('Fertilizer', 'Fertilizer'), ('Vegetable', 'Vegetable'), ('Seed', 'Seed'), ('Fruit', 'Fruit')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
