# Generated by Django 4.2.4 on 2024-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
