# Generated by Django 4.2.4 on 2024-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_report_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.CharField(default='Sanaswadi', max_length=150),
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=150),
        ),
        migrations.AddField(
            model_name='report',
            name='street',
            field=models.CharField(default='Kalubai Nagar', max_length=150),
        ),
        migrations.AddField(
            model_name='report',
            name='zip',
            field=models.CharField(default='412208', max_length=150),
        ),
    ]
